# 开发环境配置文件
# 配置数据库的连接字符串
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/oj_system?characterEncoding=utf8
    username: root
    password: zzzzzz
    driver-class-name: com.mysql.cj.jdbc.Driver
